apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-response-header
  namespace: kong
config:
  add:
    headers:
    - "demo: injected-by-kong"
plugin: response-transformer
